DROP TABLE Quizes CASCADE;
DROP TABLE Questions CASCADE;
DROP TABLE Answers CASCADE;
DROP TABLE Topics CASCADE;
DROP TABLE QuestionHasTopics CASCADE;
DROP TABLE QuestionHasCorrectAnswers CASCADE;
DROP TABLE QuestionHasImage CASCADE;
DROP TABLE QuizHasQuestions CASCADE;
